name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
